openapi: 3.0.0
info:
  title: API 316 LINE
  version: 1.0.0

paths:
  /tp/ping:
    get:
      summary: Получить информацию о доступности сервера.
      responses:
        '200':
          description: Успешный ответ.
        '500':
          description: Сервер недоступен.
  /tp/puck:
    post:
      summary: Добавление новой шайбы для начала работы ТП.
      responses:
        '200':
          description: Успешно
        '500':
          description: Возникла ошибка
  /tp/sensor/{sensor_id}:
    get:
      summary: Получение значения датчика.
      parameters:
      - name: sensor_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Значение датчика.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SensorResponse'
        '400':
          description: bad request.
        '500':
          description: Возникла ошибка.
  /tp/gripper/left:
    post:
      summary: Начать движение гриппера влево.
      responses:
        '200':
          description: Движение начато
        '500':
          description: Возникла ошибка.
  /tp/gripper/rigth:
    post:
      summary: Начать движение гриппера вправо.
      responses:
        '200':
          description: Движение начато
        '500':
          description: Возникла ошибка.
  /tp/gripper/up:
    post:
      summary: Начать движение гриппера вверх.
      responses:
        '200':
          description: Движение начато
        '500':
          description: Возникла ошибка.
  /tp/gripper/down:
    post:
      summary: Начать движение гриппера вниз.
      responses:
        '200':
          description: Движение начато
        '500':
          description: Возникла ошибка.
  /tp/gripper/open:
    post:
      summary: Открыть лапу гриппера.
      responses:
        '200':
          description: Открыта
        '500':
          description: Возникла ошибка.
  /tp/gripper/close:
    post:
      summary: Закрыть лапу гриппера.
      responses:
        '200':
          description: Открыта
        '500':
          description: Возникла ошибка.
  /tp/gripper/stop:
    post:
      summary: Остановить гриппер.
      responses:
        '200':
          description: Остановлен
        '500':
          description: Возникла ошибка.
  /tp/gripper/enable:
    post:
      summary: Включить гриппер.
      responses:
        '200':
          description: Включен
        '500':
          description: Возникла ошибка.
  /tp/carousel/rotate:
    post:
      summary: Повернуть карусель на 1 слот
      responses:
        '200':
          description: Успешно
        '500':
          description: Возникла ошибка.
  /tp/carousel/inspect:
    post:
      summary: Проверка заготовки
      responses:
        '200':
          description: Успешно
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InspectResponse'
        '500':
          description: Возникла ошибка.
  /tp/carousel/drill:
    post:
      summary: Сверление заготовки
      responses:
        '200':
          description: Успешно
        '500':
          description: Возникла ошибка.
  /tp/packaging/pack:
    post:
      summary: Начать упаковку заготовки
      responses:
        '200':
          description: Успешно
        '500':
          description: Возникла ошибка.
  /tp/sorting/sort:
    post:
      summary: Начать сортировку заготовки
      responses:
        '200':
          description: Успешно
        '500':
          description: Возникла ошибка.


components:
  schemas:
    SensorResponse:
      type: object
      properties:
        value:
          type: boolean
          description: Значение датчика
    InspectResponse:
      type: object
      properties:
        color:
          type: string
          description: Цвет заготовки
